### ISSUE TITLE
Assembly to improve the speed... 🤔 

### ISSUE THREAD

**Issue by RolEYder** [hinton-lang/Hinton#2]
Is possible to execute some instructions using Assembly code to improve the compile speed? Yes using the Java Native Interface Specification[1] you can execute inlining code on Java.  Here an example:

Consider the following instructions 
```java
public class MyClass {
 public native void exampleFunction() {

  }
}
```
Is possible to manage this snipping code from the assembly function using `Java_MyClass_exampleFunction`. This function can be called from the assembly in the execution process as: 
```assembly
global Java_MyClass_exampleFunction

section .text
           Java_MyClass_exampleFunction
           mov aex, aex
           mov epx, [aex]
            ...
```

To know more about how to run inline code using Java and Assembly see the reference below. I hope this information can solve the time compile execution performance🤞 

### Resources
1. https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/jniTOC.html

**Comment by faustotnc** [comment]
Hey @RolEYder! This is very interesting. I had no idea it was possible to embed assembly code within Java. I will definitely look into this later to learn more about it.

I have decided to dive deep into the second section of the [Crafting Interpreters](https://craftinginterpreters.com/a-bytecode-virtual-machine.html) book – namely, converting the interpreter to a bytecode compiler using C. This will be similar to what Python and the V8 engine do. With this, the interpreter will also see a great jump in performance.

I am currently in school, so I haven't had as much time to invest in Hinton. There will be more updates to the repository as soon as I go into summer break. You can visit the [C - Version](https://github.com/hinton-lang/Hinton/tree/c-version) branch to look at the current state of the C bytecode compiler.

I think that maybe once Hinton becomes more mature (and I get at least 100 users 😅) I will find a way of parsing certain parts of the source code directly to assembly.
